### ISSUE TITLE
Unknown module: "gd_client_oauth"

### ISSUE THREAD

**Issue by scoobymooch** [wavemaking/GooglePhotosSync#1]
Hi there,

I'm trying to use your Google Photos Sync module, but it imports "gd_client_oauth" and I can't find this available anywhere. Could you give me a pointer on where to find it?

Best,
Matt

**Comment by scoobymooch** [comment]
Hi there,

I found code elsewhere and created the oauth module needed.

Best,
Matt

**Comment by wavemaking** [comment]
My bad. This module was missing from the repository. Thanks for noticing. I added it now.  Please bear in mind that in any case this project does have some other issues still, also due to change of the Google Picasa API. I'm working on some improvements. When done I'll push these to the repository.
