### ISSUE TITLE
How to use it

### ISSUE THREAD

**Issue by emmtte** [wavemaking/GooglePhotosSync#2]
I have this Error

```
 sudo python main.py
Traceback (most recent call last):
  File "main.py", line 36, in <module>
    os.chdir(os.path.dirname(getsourcefile(lambda:0)))
OSError: [Errno 2] No such file or directory: ''
```

**Comment by wavemaking** [comment]
That's odd. That line is intended to change the python interpreter to the directory that also contains main.py . It appears that the line returns an empty path an thus, the chdir call fails. What's the environment where you run the program? Python version, operating system? If you run the program from the directory that contains main.py (and settings.py) then you could run without this line (just comment or delete it).
